services:
  rag-app:
    build: .
    container_name: rag_chatbot
    volumes:
      - .:/app
    ports:
      - "8501:8501"  # If using Streamlit
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    command: bash -c "python create_database.py && streamlit run app.py"

